### ISSUE TITLE
Convert  a set to data model

### ISSUE THREAD

**Issue by sbelmeha** [tucan9389/KeypointAnnotation#5]
Could you add some tutorial (or links) how to convert resulted dataset to Tensorflow or Core ML data model?

**Comment by sbelmeha** [comment]
ok, looks like I figured out how to train it using https://github.com/edvardHua/PoseEstimationForMobile
I'm interesting, how much images do I need just to test it? I have tried with 15 images and nothing happens (maybe my mv2_cpm.cfg is wrong), I don't need it to work perfectly, just to ensure that core ml model was created correctly.

**Comment by tucan9389** [comment]
I think you should follow readme of PoseEstimationForMobile project first.
At the first try just use given dataset on the repo(not your own dataset).

**Comment by baptadn** [comment]
Hi there! Do you know why the https://github.com/edvardHua/PoseEstimationForMobile repo redirects to a 404 not found ?

**Comment by tucan9389** [comment]
OMG

**Comment by tucan9389** [comment]
https://github.com/tucan9389/pose-estimation-for-mobile
Here I recovered the latest version of PoseEstimationForMobile repo temporarily.
